name: Documentation version release

on:
  workflow_dispatch:
    inputs:
      create-branch:
        description: "Branch name"
      version:
        description: "RELEASE_VERSION"

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#       - name: Create report file
#         run: date +%s > report.txt
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Add report file
          labels: report, automated pr
