name: Documentation version release

on:
  workflow_dispatch:
    inputs:
      create-branch:
        description: "Branch name"
      version:
        description: "RELEASE_VERSION"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: extract git commmit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Create Pull Request
        id: doc
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "auto"
          base: "main"
          delete-branch : true
          token: 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
